title:       Alex J
author:      Alex Jackson

safe:        false
port: 4000
baseurl:    /
url: http://alexj.org 

source:      .
destination: ./_site
plugins:     ./_plugins

paginate: 5
future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /:month/:title/

rdiscount:
  extensions: 
  - footnotes
  - smart
  - autolink
