baseurl = "https://alexj.org"
title = "Alex J"

paginate = 5

[author]
  name = "Alex Jackson"
  email = "alex@alexj.org"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:month/:filename/"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "manni"

[outputs]
home = ["RSS", "HTML"]
section = ["HTML"]
