baseurl = "https://alexj.org"
title = "Alex J"

paginate = 5

pygmentsuseclasses = false
pygmentscodefences = true
pygmentsstyle = "manni"

[taxonomies]
tag = "tags"

[permalinks]
post = "/:month/:filename/"
