baseurl = "https://alexj.org"
title = "Alex J"

paginate = 5

pygmentsuseclasses = false
pygmentscodefences = true
pygmentsstyle = "manni"

[author]
  name = "Alex Jackson"
  email = "alex@alexj.org"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:month/:filename/"
